name: test jeu keep-white-space

on:
  push:
    branches: [ "dev", "main", "feature/*" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. installer les dependances
      - name: Install dependencies
        run: npm install
        working-directory: js-game-keep-white-space

      # 4. lancer les tests
      - name: Run tests
        run: npm test
        working-directory: js-game-keep-white-space

      # 5. lancer le Audit
      - name: Security audit
        run: npm audit --audit-level=high
        working-directory: js-game-keep-white-space

      # 6. Dockerfile
      - name: Build Docker image
        run: docker build -t mon-jeu .
        working-directory: js-game-keep-white-space

      # 7. Deployement du jeux
      - name: Deploy
        run: echo "Déploiement OK"
