name: CI Game 1 - Two Ships

on:
  push:
    branches:
        - 'main'
        - 'TwoShips'
    paths: [TwoShips/**]

#   pull_request:
#     branches:
#         - 'TwoShips'
#     paths: [TwoShips/**]

  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with: 
                node-version: 16.13.x
                cache: npm
                cache-dependency-path: TwoShips/package-lock.json

            - name: Install dependencies
              run: npm ci
              working-directory: ./TwoShips

            - name: Run Linter
              run: npm run lint
              working-directory: ./TwoShips

            - name: Security Audit
              run: npm audit --audit-level=critical
              working-directory: ./TwoShips

            - name: Run Tests & Coverage
              run: npm run test:coverage
              working-directory: ./TwoShips

            - name: Notify Failure
              if: failure()
              run: |
                curl -H "Content-Type: application/json" \
                    -d '{
                      "content": "❌ **Échec du Pipeline TwoShips !**\n**Branche :** ${{ github.ref_name }}\n**Commit :** ${{ github.sha }}\n**Lien vers l erreur :** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }' \
                    ${{ secrets.DISCORD_WEBHOOK }}